Search by name for set
sanger/aker-sets pull request #136
Opened 2018-03-07 16:52 UTC by emrojo

2018-03-07 17:00 UTC, emrojo commented
Depends on https://github.com/sanger/aker-set-service/pull/65

2018-03-09 09:34 UTC, NikolausC requested changes

2018-03-09 09:34 UTC, NikolausC commented on app/client/components/set_selector.es6
> +    return fetch(`/sets_service/sets?filter[search_by_name]=${value}`)
I think we should also filter by locked sets, as those are showing up in the results

2018-03-09 10:04 UTC, NikolausC approved these changes

2018-03-09 10:04 UTC, merged